### ISSUE TITLE
How can I adjust the width of the date picker?

### ISSUE THREAD

**Issue by AshleySetter** [Kiarash-Z/react-modern-calendar-datepicker#162]
How can I adjust the width of the datepicker? So if I have a basic datepicker like in[ this sandbox ](https://codesandbox.io/s/app-drawer-menu-with-datepicker-4wlxc). How can I adjust the width so it's not got lots of whitespace around the actual date? It's almost twice as wide as it needs to be.

**Comment by Kiarash-Z** [comment]
Hi, you can scale down the whole calendar [by specifying a font-size for the calendar](https://kiarash-z.github.io/react-modern-calendar-datepicker/docs/responsive-guide) using `calendarClassName` prop:

```css
.scaled-down-calendar {
  /* by setting font-size, all the elements will correspond */
  font-size: 8px !important; /* default to 10px */
}
```

**Comment by AshleySetter** [comment]
Ah, ok, is there not a way to scale down the datepicker independent of the font size? For example if I wanted the edges of the datepicker box to be close to the edges of the date text?

**Comment by AshleySetter** [comment]
I was thinking of reducing the width like the box on the right here:

![Screenshot from 2020-06-12 12 40 54](https://user-images.githubusercontent.com/14869658/84499493-9dcb8500-acaa-11ea-992c-fbd6cdd3eb22.png)

**Comment by Kiarash-Z** [comment]
@AshleySetter Sorry for the latency in response. Do you want to reduce the space between the days and the calendar's left/right boundaries?

**Comment by AshleySetter** [comment]
No worries, yes, that was what I had in mind.

**Comment by Kiarash-Z** [comment]
There are a few styles that you need to override. [I made a demo on CodeSandbox for that](https://codesandbox.io/s/small-bird-9csj6?file=/src/App.js). Here's how the code looks like there:

First off, we give the calendar a custom class:
```js
<Calendar
  value={value}
  onChange={setValue}
  calendarClassName="myCustomCalendar" {/* Giving a custom class to the calendar */}
/>
```

Then we override the styles based on that:
```css
.myCustomCalendar {
  width: 29em !important; /* previously was 33em */
}

.myCustomCalendar .Calendar__section.-hiddenNext {
  transform: translateX(100%); /* previously was 90% */
}

.myCustomCalendar .Calendar__section.-hiddenPrevious {
  transform: translateX(-100%); /* previously was -90% */
}

.myCustomCalendar .Calendar__section {
  padding: 0 1em; /* previously was 0 3.2em */
}

.myCustomCalendar .Calendar__weekDays {
  padding: 0 0.8em; /* previously was 0 2.6em */
}
```

I really apologize for the latency in response 🙏🏻 I hope this is helpful.
